package SoSeWorksheet.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class BoolParameter_Constraints extends BaseConstraintsDescriptor {
  public BoolParameter_Constraints() {
    super(CONCEPTS.BoolParameter$l5);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept BoolParameter$l5 = MetaAdapterFactory.getConcept(0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x6a561a266a1c17a5L, "SoSeWorksheet.structure.BoolParameter");
  }
}
