package SoSeWorksheet.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class FunctionCall_Constraints extends BaseConstraintsDescriptor {
  public FunctionCall_Constraints() {
    super(CONCEPTS.FunctionCall$Vk);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept FunctionCall$Vk = MetaAdapterFactory.getConcept(0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x6ba37e7ec88b26c7L, "SoSeWorksheet.structure.FunctionCall");
  }
}
