package SoSeWorksheet.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class IParam_Constraints extends BaseConstraintsDescriptor {
  public IParam_Constraints() {
    super(CONCEPTS.IParam$D3);
  }

  private static final class CONCEPTS {
    /*package*/ static final SInterfaceConcept IParam$D3 = MetaAdapterFactory.getInterfaceConcept(0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x1d9591cece35380dL, "SoSeWorksheet.structure.IParam");
  }
}
