package SoSeWorksheet.Interpreter.plugin;

/*Generated by MPS */

import jetbrains.mps.smodel.structure.DefaultExtensionDescriptor;
import java.util.Arrays;

public class ExtensionDescriptor extends DefaultExtensionDescriptor {
  public ExtensionDescriptor() {
    super(null, Arrays.asList(new SoSeWorksheetInterpreter_extension()));
  }
}
