package SoSeWorksheet.Interpreter.plugin;

/*Generated by MPS */

import jetbrains.mps.smodel.structure.Extension;
import com.mbeddr.mpsutil.interpreter.rt.IInterpreter;
import com.mbeddr.mpsutil.interpreter.rt.CachedInterpreterFinder;

public class SoSeWorksheetInterpreter_extension extends Extension.Default<IInterpreter> {
  public SoSeWorksheetInterpreter_extension() {
    super("com.mbeddr.mpsutil.interpreter.InterpreterExtensionPoint");
  }

  public void activate() {
    CachedInterpreterFinder.getInstance().flushCache();
  }
  public void deactivate() {
    CachedInterpreterFinder.getInstance().flushCache();
  }

  public IInterpreter get() {
    return new InterpreterSoSeWorksheetInterpreter();
  }
}
