package SoSeWorksheet.runtime;

/*Generated by MPS */


public class TestWorksheet {
  public static void main() {
    boolean globalBool = true;
    int globalInt = 42 - 5 + 2;
    int globalInt2 = 12 + 2 * 3;
    int globalInt3 = 12 * (12 + 12);
    boolean bool1 = globalInt == globalInt2;
    Dog dog = new Dog();
    dog.setAge(globalInt, globalBool);
    globalBool = dog.isMale;
    globalInt = dog.age + globalInt;
    if (globalBool == globalBool) {
      globalBool = false;
    }
    for (int i = 1; i < 100; i = i + 1) {
      globalInt = globalInt + 1;
    }
    while (globalBool) {
      globalBool = false;
    }
  }
  private static class Dog {
    private boolean isMale = false;
    private int age = 0;
    private boolean a = false;
    public int setAge(int a, boolean isDead) {
      age = a;
      return a;
    }
    public boolean setGenderToMale() {
      isMale = true;
      return false;
    }
    public int add(int x, int y) {
      return x + y;
    }
  }
}
