package SoSeLanguage22.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int IStatement = 0;
  public static final int SoSeWorksheet = 1;
  public static final int VariableDeclaration = 2;
  public static final int boolType = 3;
  public static final int intType = 4;
  public static final int refVar = 5;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xdfcb7723c3fd4b94L, 0xabab01861ff66059L);
    builder.put(0x71f8990146219dc3L, IStatement);
    builder.put(0x3d4b3825e5976076L, SoSeWorksheet);
    builder.put(0x271d5685a1907740L, VariableDeclaration);
    builder.put(0x3d4b3825e5976078L, boolType);
    builder.put(0x3d4b3825e5976074L, intType);
    builder.put(0x3d4b3825e597607aL, refVar);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
