package SoSeLanguage22.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptIStatement = createDescriptorForIStatement();
  /*package*/ final ConceptDescriptor myConceptSoSeWorksheet = createDescriptorForSoSeWorksheet();
  /*package*/ final ConceptDescriptor myConceptVariableDeclaration = createDescriptorForVariableDeclaration();
  /*package*/ final ConceptDescriptor myConceptboolType = createDescriptorForboolType();
  /*package*/ final ConceptDescriptor myConceptintType = createDescriptorForintType();
  /*package*/ final ConceptDescriptor myConceptrefVar = createDescriptorForrefVar();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptIStatement, myConceptSoSeWorksheet, myConceptVariableDeclaration, myConceptboolType, myConceptintType, myConceptrefVar);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.IStatement:
        return myConceptIStatement;
      case LanguageConceptSwitch.SoSeWorksheet:
        return myConceptSoSeWorksheet;
      case LanguageConceptSwitch.VariableDeclaration:
        return myConceptVariableDeclaration;
      case LanguageConceptSwitch.boolType:
        return myConceptboolType;
      case LanguageConceptSwitch.intType:
        return myConceptintType;
      case LanguageConceptSwitch.refVar:
        return myConceptrefVar;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForIStatement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoSeLanguage22", "IStatement", 0xdfcb7723c3fd4b94L, 0xabab01861ff66059L, 0x71f8990146219dc3L);
    b.interface_();
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b04d0603-57fa-4abb-8b3e-a223c8ea80e7(SoSeLanguage22.structure)/8212482151260724675");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSoSeWorksheet() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoSeLanguage22", "SoSeWorksheet", 0xdfcb7723c3fd4b94L, 0xabab01861ff66059L, 0x3d4b3825e5976076L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b04d0603-57fa-4abb-8b3e-a223c8ea80e7(SoSeLanguage22.structure)/4416685594983751798");
    b.version(3);
    b.aggregate("contents", 0x71f8990146219dc8L).target(0xdfcb7723c3fd4b94L, 0xabab01861ff66059L, 0x71f8990146219dc3L).optional(true).ordered(true).multiple(true).origin("8212482151260724680").done();
    b.alias("SoSeWorksheet");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForVariableDeclaration() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoSeLanguage22", "VariableDeclaration", 0xdfcb7723c3fd4b94L, 0xabab01861ff66059L, 0x271d5685a1907740L);
    b.class_(false, false, false);
    b.parent(0xdfcb7723c3fd4b94L, 0xabab01861ff66059L, 0x71f8990146219dc3L);
    b.origin("r:b04d0603-57fa-4abb-8b3e-a223c8ea80e7(SoSeLanguage22.structure)/2818504073745037120");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForboolType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoSeLanguage22", "boolType", 0xdfcb7723c3fd4b94L, 0xabab01861ff66059L, 0x3d4b3825e5976078L);
    b.class_(false, false, false);
    b.parent(0xdfcb7723c3fd4b94L, 0xabab01861ff66059L, 0x71f8990146219dc3L);
    b.origin("r:b04d0603-57fa-4abb-8b3e-a223c8ea80e7(SoSeLanguage22.structure)/4416685594983751800");
    b.version(3);
    b.alias("bool");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForintType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoSeLanguage22", "intType", 0xdfcb7723c3fd4b94L, 0xabab01861ff66059L, 0x3d4b3825e5976074L);
    b.class_(false, false, false);
    b.parent(0xdfcb7723c3fd4b94L, 0xabab01861ff66059L, 0x71f8990146219dc3L);
    b.origin("r:b04d0603-57fa-4abb-8b3e-a223c8ea80e7(SoSeLanguage22.structure)/4416685594983751796");
    b.version(3);
    b.alias("int");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForrefVar() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoSeLanguage22", "refVar", 0xdfcb7723c3fd4b94L, 0xabab01861ff66059L, 0x3d4b3825e597607aL);
    b.class_(false, false, false);
    b.parent(0xdfcb7723c3fd4b94L, 0xabab01861ff66059L, 0x71f8990146219dc3L);
    b.origin("r:b04d0603-57fa-4abb-8b3e-a223c8ea80e7(SoSeLanguage22.structure)/4416685594983751802");
    b.version(3);
    b.associate("refTo", 0x71f899014624146dL).target(0xdfcb7723c3fd4b94L, 0xabab01861ff66059L, 0x71f8990146219dc3L).optional(false).origin("8212482151260886125").done();
    b.alias("ref");
    return b.create();
  }
}
