package SoSeWorksheet.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptBoolVar = createDescriptorForBoolVar();
  /*package*/ final ConceptDescriptor myConceptEmptyLine = createDescriptorForEmptyLine();
  /*package*/ final ConceptDescriptor myConceptIVarContent = createDescriptorForIVarContent();
  /*package*/ final ConceptDescriptor myConceptIntLiteral = createDescriptorForIntLiteral();
  /*package*/ final ConceptDescriptor myConceptIntVar = createDescriptorForIntVar();
  /*package*/ final ConceptDescriptor myConceptLeftVar = createDescriptorForLeftVar();
  /*package*/ final ConceptDescriptor myConceptPlusExpression = createDescriptorForPlusExpression();
  /*package*/ final ConceptDescriptor myConceptRightVar = createDescriptorForRightVar();
  /*package*/ final ConceptDescriptor myConceptTwoValues = createDescriptorForTwoValues();
  /*package*/ final ConceptDescriptor myConceptTwoVars = createDescriptorForTwoVars();
  /*package*/ final ConceptDescriptor myConceptVariableDefine = createDescriptorForVariableDefine();
  /*package*/ final ConceptDescriptor myConceptVariableRef = createDescriptorForVariableRef();
  /*package*/ final ConceptDescriptor myConceptWorksheet = createDescriptorForWorksheet();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptBoolVar, myConceptEmptyLine, myConceptIVarContent, myConceptIntLiteral, myConceptIntVar, myConceptLeftVar, myConceptPlusExpression, myConceptRightVar, myConceptTwoValues, myConceptTwoVars, myConceptVariableDefine, myConceptVariableRef, myConceptWorksheet);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.BoolVar:
        return myConceptBoolVar;
      case LanguageConceptSwitch.EmptyLine:
        return myConceptEmptyLine;
      case LanguageConceptSwitch.IVarContent:
        return myConceptIVarContent;
      case LanguageConceptSwitch.IntLiteral:
        return myConceptIntLiteral;
      case LanguageConceptSwitch.IntVar:
        return myConceptIntVar;
      case LanguageConceptSwitch.LeftVar:
        return myConceptLeftVar;
      case LanguageConceptSwitch.PlusExpression:
        return myConceptPlusExpression;
      case LanguageConceptSwitch.RightVar:
        return myConceptRightVar;
      case LanguageConceptSwitch.TwoValues:
        return myConceptTwoValues;
      case LanguageConceptSwitch.TwoVars:
        return myConceptTwoVars;
      case LanguageConceptSwitch.VariableDefine:
        return myConceptVariableDefine;
      case LanguageConceptSwitch.VariableRef:
        return myConceptVariableRef;
      case LanguageConceptSwitch.Worksheet:
        return myConceptWorksheet;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForBoolVar() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoSeWorksheet", "BoolVar", 0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x72373ee575935b00L);
    b.class_(false, false, false);
    // extends: SoSeWorksheet.structure.VariableDefine
    b.super_(0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x72373ee575935a33L);
    b.origin("r:f7a85c17-cbe9-43ba-9dd9-8a98add99604(SoSeWorksheet.structure)/8230115999283895040");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEmptyLine() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoSeWorksheet", "EmptyLine", 0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x1ee4a93c3ed81300L);
    b.class_(false, false, false);
    b.parent(0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x72373ee5759461d5L);
    b.origin("r:f7a85c17-cbe9-43ba-9dd9-8a98add99604(SoSeWorksheet.structure)/2226090192045347584");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIVarContent() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoSeWorksheet", "IVarContent", 0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x72373ee5759461d5L);
    b.interface_();
    b.origin("r:f7a85c17-cbe9-43ba-9dd9-8a98add99604(SoSeWorksheet.structure)/8230115999283962325");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIntLiteral() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoSeWorksheet", "IntLiteral", 0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x1ee4a93c3ec90fd4L);
    b.class_(false, false, false);
    b.parent(0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x72373ee5759461d5L);
    b.origin("r:f7a85c17-cbe9-43ba-9dd9-8a98add99604(SoSeWorksheet.structure)/2226090192044363732");
    b.version(3);
    b.property("value", 0x1ee4a93c3ec90fd5L).type(PrimitiveTypeId.STRING).origin("2226090192044363733").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIntVar() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoSeWorksheet", "IntVar", 0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x72373ee575935b01L);
    b.class_(false, false, false);
    // extends: SoSeWorksheet.structure.VariableDefine
    b.super_(0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x72373ee575935a33L);
    b.origin("r:f7a85c17-cbe9-43ba-9dd9-8a98add99604(SoSeWorksheet.structure)/8230115999283895041");
    b.version(3);
    b.aggregate("value", 0x1ee4a93c3ed7832aL).target(0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x1ee4a93c3ec90fd4L).optional(false).ordered(true).multiple(false).origin("2226090192045310762").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLeftVar() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoSeWorksheet", "LeftVar", 0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x1ee4a93c3ecc31c5L);
    b.class_(false, false, false);
    b.parent(0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x73aac863fbaf8321L);
    b.origin("r:f7a85c17-cbe9-43ba-9dd9-8a98add99604(SoSeWorksheet.structure)/2226090192044569029");
    b.version(3);
    b.associate("left", 0x1ee4a93c3ed1bda2L).target(0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x72373ee575935b01L).optional(false).origin("2226090192044932514").done();
    b.aggregate("right", 0x1ee4a93c3ecc31ccL).target(0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x1ee4a93c3ec90fd4L).optional(false).ordered(true).multiple(false).origin("2226090192044569036").done();
    b.alias("+");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPlusExpression() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoSeWorksheet", "PlusExpression", 0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x73aac863fbaf8321L);
    b.interface_();
    b.parent(0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x72373ee5759461d5L);
    b.origin("r:f7a85c17-cbe9-43ba-9dd9-8a98add99604(SoSeWorksheet.structure)/8334694392152425249");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRightVar() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoSeWorksheet", "RightVar", 0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x1ee4a93c3ed24fe0L);
    b.class_(false, false, false);
    b.parent(0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x73aac863fbaf8321L);
    b.origin("r:f7a85c17-cbe9-43ba-9dd9-8a98add99604(SoSeWorksheet.structure)/2226090192044969952");
    b.version(3);
    b.associate("right", 0x1ee4a93c3ed418b8L).target(0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x72373ee575935b01L).optional(false).origin("2226090192045086904").done();
    b.aggregate("left", 0x1ee4a93c3ed24fe2L).target(0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x1ee4a93c3ec90fd4L).optional(false).ordered(true).multiple(false).origin("2226090192044969954").done();
    b.alias("+");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTwoValues() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoSeWorksheet", "TwoValues", 0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x73aac863fbaf8325L);
    b.class_(false, false, false);
    b.parent(0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x73aac863fbaf8321L);
    b.origin("r:f7a85c17-cbe9-43ba-9dd9-8a98add99604(SoSeWorksheet.structure)/8334694392152425253");
    b.version(3);
    b.aggregate("left", 0x1ee4a93c3ed05113L).target(0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x1ee4a93c3ec90fd4L).optional(false).ordered(true).multiple(false).origin("2226090192044839187").done();
    b.aggregate("right", 0x1ee4a93c3ed05115L).target(0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x1ee4a93c3ec90fd4L).optional(false).ordered(true).multiple(false).origin("2226090192044839189").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTwoVars() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoSeWorksheet", "TwoVars", 0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x73aac863fbaf20c3L);
    b.class_(false, false, false);
    b.parent(0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x73aac863fbaf8321L);
    b.origin("r:f7a85c17-cbe9-43ba-9dd9-8a98add99604(SoSeWorksheet.structure)/8334694392152400067");
    b.version(3);
    b.associate("first", 0x73aac863fbaf7b3eL).target(0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x72373ee575935b01L).optional(false).origin("8334694392152423230").done();
    b.associate("second", 0x73aac863fbaf7ff4L).target(0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x72373ee575935b01L).optional(false).origin("8334694392152424436").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForVariableDefine() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoSeWorksheet", "VariableDefine", 0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x72373ee575935a33L);
    b.class_(false, false, false);
    b.parent(0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x72373ee5759461d5L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f7a85c17-cbe9-43ba-9dd9-8a98add99604(SoSeWorksheet.structure)/8230115999283894835");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForVariableRef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoSeWorksheet", "VariableRef", 0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x72373ee575935a3fL);
    b.class_(false, false, false);
    b.parent(0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x72373ee5759461d5L);
    b.origin("r:f7a85c17-cbe9-43ba-9dd9-8a98add99604(SoSeWorksheet.structure)/8230115999283894847");
    b.version(3);
    b.associate("var", 0x1a917f7ad1bc8bdaL).target(0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x72373ee575935a33L).optional(false).origin("1914451482090703834").done();
    b.alias("ref");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForWorksheet() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoSeWorksheet", "Worksheet", 0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x72373ee5759225b2L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f7a85c17-cbe9-43ba-9dd9-8a98add99604(SoSeWorksheet.structure)/8230115999283815858");
    b.version(3);
    b.aggregate("vars", 0x72373ee57593ae90L).target(0xc0ccb3a7555a492dL, 0x87ab866148bc2243L, 0x72373ee5759461d5L).optional(true).ordered(true).multiple(true).origin("8230115999283916432").done();
    b.alias("SoSeWorksheet");
    return b.create();
  }
}
